//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""40274b66-c32a-4092-81ce-a8001c708fb1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6febe845-b201-48a9-8cd2-5385ab9fef56"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""3761002b-740f-4597-a6c6-dbcb761abdf2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9ebb7c22-2a2d-408e-af28-e7af3d05fedc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""36b60082-60da-4ef7-9fa6-c9b387d4af94"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d4036b23-c12c-4f8a-a9fe-c7a9b3a6a7b2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""07b9c045-6bc7-483c-9a59-6f724cec8fc5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""254736f5-6902-44d7-857f-97425edea441"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""393b1e9d-9131-4f09-b113-411d0f6d5941"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Buider"",
            ""id"": ""18aa8c0a-820c-4a9d-bef4-2dd5b1c29019"",
            ""actions"": [
                {
                    ""name"": ""ExitBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""f3e47b9a-6cf6-4e53-9bf1-89b32b5fa625"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a46d7310-8212-487f-b128-36ea25745f76"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Alternatives"",
            ""id"": ""f2d674c0-988a-4781-b088-8e0f7acf2755"",
            ""actions"": [
                {
                    ""name"": ""Shift"",
                    ""type"": ""Button"",
                    ""id"": ""1d37834d-0168-4011-9666-c4bea83f64be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Control"",
                    ""type"": ""Button"",
                    ""id"": ""17da45f5-ca35-41b3-a6e9-11693714bab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alt"",
                    ""type"": ""Button"",
                    ""id"": ""2eb47871-9914-4d49-a233-bd863ab0aa22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1681ce5c-dde5-472d-8c85-939b7707d065"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fecdd23-50f1-4b49-99ae-59f92b8da150"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df8084c1-080c-477d-8c94-cab1fbfe6fe2"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Generics"",
            ""id"": ""3423f8ff-5860-4ec0-b8c1-8e3d09ee5c86"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""e5a1ca2b-9a03-4807-8fcd-cf926a262825"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""a90a9a2e-8249-4b9e-a8b5-08fc9f7a8974"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""c63413fc-9680-4b70-a8b3-f01f7acf6c3b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29e9eef7-296e-4ea8-9924-8a33a9d27993"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09d46fbd-f1af-4384-a5fb-f7db8c86eec1"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d09b4004-4940-4db6-8788-c866e7f3c4ed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_EnterBuildMode = m_Player.FindAction("EnterBuildMode", throwIfNotFound: true);
        // Buider
        m_Buider = asset.FindActionMap("Buider", throwIfNotFound: true);
        m_Buider_ExitBuildMode = m_Buider.FindAction("ExitBuildMode", throwIfNotFound: true);
        // Alternatives
        m_Alternatives = asset.FindActionMap("Alternatives", throwIfNotFound: true);
        m_Alternatives_Shift = m_Alternatives.FindAction("Shift", throwIfNotFound: true);
        m_Alternatives_Control = m_Alternatives.FindAction("Control", throwIfNotFound: true);
        m_Alternatives_Alt = m_Alternatives.FindAction("Alt", throwIfNotFound: true);
        // Generics
        m_Generics = asset.FindActionMap("Generics", throwIfNotFound: true);
        m_Generics_Select = m_Generics.FindAction("Select", throwIfNotFound: true);
        m_Generics_Cancel = m_Generics.FindAction("Cancel", throwIfNotFound: true);
        m_Generics_Scroll = m_Generics.FindAction("Scroll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_EnterBuildMode;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @EnterBuildMode => m_Wrapper.m_Player_EnterBuildMode;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @EnterBuildMode.started += instance.OnEnterBuildMode;
            @EnterBuildMode.performed += instance.OnEnterBuildMode;
            @EnterBuildMode.canceled += instance.OnEnterBuildMode;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @EnterBuildMode.started -= instance.OnEnterBuildMode;
            @EnterBuildMode.performed -= instance.OnEnterBuildMode;
            @EnterBuildMode.canceled -= instance.OnEnterBuildMode;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Buider
    private readonly InputActionMap m_Buider;
    private List<IBuiderActions> m_BuiderActionsCallbackInterfaces = new List<IBuiderActions>();
    private readonly InputAction m_Buider_ExitBuildMode;
    public struct BuiderActions
    {
        private @PlayerInputActions m_Wrapper;
        public BuiderActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ExitBuildMode => m_Wrapper.m_Buider_ExitBuildMode;
        public InputActionMap Get() { return m_Wrapper.m_Buider; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuiderActions set) { return set.Get(); }
        public void AddCallbacks(IBuiderActions instance)
        {
            if (instance == null || m_Wrapper.m_BuiderActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuiderActionsCallbackInterfaces.Add(instance);
            @ExitBuildMode.started += instance.OnExitBuildMode;
            @ExitBuildMode.performed += instance.OnExitBuildMode;
            @ExitBuildMode.canceled += instance.OnExitBuildMode;
        }

        private void UnregisterCallbacks(IBuiderActions instance)
        {
            @ExitBuildMode.started -= instance.OnExitBuildMode;
            @ExitBuildMode.performed -= instance.OnExitBuildMode;
            @ExitBuildMode.canceled -= instance.OnExitBuildMode;
        }

        public void RemoveCallbacks(IBuiderActions instance)
        {
            if (m_Wrapper.m_BuiderActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuiderActions instance)
        {
            foreach (var item in m_Wrapper.m_BuiderActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuiderActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuiderActions @Buider => new BuiderActions(this);

    // Alternatives
    private readonly InputActionMap m_Alternatives;
    private List<IAlternativesActions> m_AlternativesActionsCallbackInterfaces = new List<IAlternativesActions>();
    private readonly InputAction m_Alternatives_Shift;
    private readonly InputAction m_Alternatives_Control;
    private readonly InputAction m_Alternatives_Alt;
    public struct AlternativesActions
    {
        private @PlayerInputActions m_Wrapper;
        public AlternativesActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shift => m_Wrapper.m_Alternatives_Shift;
        public InputAction @Control => m_Wrapper.m_Alternatives_Control;
        public InputAction @Alt => m_Wrapper.m_Alternatives_Alt;
        public InputActionMap Get() { return m_Wrapper.m_Alternatives; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AlternativesActions set) { return set.Get(); }
        public void AddCallbacks(IAlternativesActions instance)
        {
            if (instance == null || m_Wrapper.m_AlternativesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AlternativesActionsCallbackInterfaces.Add(instance);
            @Shift.started += instance.OnShift;
            @Shift.performed += instance.OnShift;
            @Shift.canceled += instance.OnShift;
            @Control.started += instance.OnControl;
            @Control.performed += instance.OnControl;
            @Control.canceled += instance.OnControl;
            @Alt.started += instance.OnAlt;
            @Alt.performed += instance.OnAlt;
            @Alt.canceled += instance.OnAlt;
        }

        private void UnregisterCallbacks(IAlternativesActions instance)
        {
            @Shift.started -= instance.OnShift;
            @Shift.performed -= instance.OnShift;
            @Shift.canceled -= instance.OnShift;
            @Control.started -= instance.OnControl;
            @Control.performed -= instance.OnControl;
            @Control.canceled -= instance.OnControl;
            @Alt.started -= instance.OnAlt;
            @Alt.performed -= instance.OnAlt;
            @Alt.canceled -= instance.OnAlt;
        }

        public void RemoveCallbacks(IAlternativesActions instance)
        {
            if (m_Wrapper.m_AlternativesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAlternativesActions instance)
        {
            foreach (var item in m_Wrapper.m_AlternativesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AlternativesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AlternativesActions @Alternatives => new AlternativesActions(this);

    // Generics
    private readonly InputActionMap m_Generics;
    private List<IGenericsActions> m_GenericsActionsCallbackInterfaces = new List<IGenericsActions>();
    private readonly InputAction m_Generics_Select;
    private readonly InputAction m_Generics_Cancel;
    private readonly InputAction m_Generics_Scroll;
    public struct GenericsActions
    {
        private @PlayerInputActions m_Wrapper;
        public GenericsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Generics_Select;
        public InputAction @Cancel => m_Wrapper.m_Generics_Cancel;
        public InputAction @Scroll => m_Wrapper.m_Generics_Scroll;
        public InputActionMap Get() { return m_Wrapper.m_Generics; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GenericsActions set) { return set.Get(); }
        public void AddCallbacks(IGenericsActions instance)
        {
            if (instance == null || m_Wrapper.m_GenericsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GenericsActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
        }

        private void UnregisterCallbacks(IGenericsActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
        }

        public void RemoveCallbacks(IGenericsActions instance)
        {
            if (m_Wrapper.m_GenericsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGenericsActions instance)
        {
            foreach (var item in m_Wrapper.m_GenericsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GenericsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GenericsActions @Generics => new GenericsActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnEnterBuildMode(InputAction.CallbackContext context);
    }
    public interface IBuiderActions
    {
        void OnExitBuildMode(InputAction.CallbackContext context);
    }
    public interface IAlternativesActions
    {
        void OnShift(InputAction.CallbackContext context);
        void OnControl(InputAction.CallbackContext context);
        void OnAlt(InputAction.CallbackContext context);
    }
    public interface IGenericsActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
    }
}
