name: Server Build for ARM64

on:
  push:
    branches:
      - milhouzer/develop
  pull_request:
    branches:
      - milhouzer/develop

jobs:
  buildServer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Set up QEMU for ARM64 emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneLinux64
          restore-keys: Library-

      - name: Build Server in Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
          customImage: unityci/editor:ubuntu-2022.3.13f1-linux-il2cpp-3.1.0
          # buildMethod: BuildServer  # Use a headless build method if defined
          projectPath: "./Game/multiplayer-project"
          buildName: "game_server"
          buildsPath: "./Server_Build/"

      - name: Package Server Build in Docker Image for ARM64
        run: |
          docker buildx create --use
          IMAGE_NAME=ghcr.io/${{ github.repository }}  # Get the repository name
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/arm64 -t "${IMAGE_NAME_LOWER}/game-server:latest" -f ./Game/Dockerfile .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}  # Get the repository name
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker push "${IMAGE_NAME_LOWER}/game-server:latest"
